// scripts/regen-slots.mjs
//
// Regenerates the <!-- SLOT_BLOCK_BEGIN --> / <!-- SLOT_BLOCK_END --> region
// of assets/scenes/humanoid.xml. Emits exactly SLOT_COUNT = 8 slots.
// Idempotent — running twice produces byte-identical output.
//
// The per-slot z offset uses integer values for even i and half-step decimals
// for odd i ("-60", "-60.5", "-61", "-61.5", …) to match the current hand-
// written block byte-for-byte. The initial run against the pre-marker XML
// must produce no diff.
//
// See docs/superpowers/specs/2026-04-24-project-sprite-workflow-design.md §4.5.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const XML_PATH = resolve(__dirname, "..", "assets", "scenes", "humanoid.xml");

const SLOT_COUNT = 8;
const BEGIN = "<!-- SLOT_BLOCK_BEGIN — regenerated by scripts/regen-slots.mjs, do not edit by hand -->";
const END = "<!-- SLOT_BLOCK_END -->";
const INDENT = "    ";

function slotZ(i) {
  // i=0 → "-60", i=1 → "-60.5", i=2 → "-61", i=3 → "-61.5", …
  return i % 2 === 0 ? String(-60 - i * 0.5) : (-60 - i * 0.5).toFixed(1);
}

function slotLine(i) {
  return (
    `${INDENT}<body name="project_slot_${i}" pos="0 0 ${slotZ(i)}">` +
    `<freejoint/>` +
    `<geom type="capsule" fromto="0 0 -0.22 0 0 0.22" size="0.26" ` +
    `rgba="0.85 0.18 0.20 1" mass="2.5" friction="1.0 0.05 0.002"/>` +
    `</body>`
  );
}

function main() {
  const xml = readFileSync(XML_PATH, "utf8");

  // Preserve the file's line-ending convention so git doesn't report a
  // whitespace diff just from rewriting. Detect CRLF vs LF from the first
  // line break.
  const eol = xml.includes("\r\n") ? "\r\n" : "\n";

  const beginIdx = xml.indexOf(BEGIN);
  const endIdx = xml.indexOf(END);
  if (beginIdx === -1 || endIdx === -1) {
    console.error(
      "regen-slots: SLOT_BLOCK markers not found in assets/scenes/humanoid.xml",
    );
    process.exit(1);
  }
  if (endIdx < beginIdx) {
    console.error("regen-slots: SLOT_BLOCK_END appears before SLOT_BLOCK_BEGIN");
    process.exit(1);
  }

  // Rebuild the block, indented with 4 spaces, each line joined by the file's
  // native EOL. The marker comments themselves sit on their own lines at the
  // same indent level as the bodies.
  const lines = [];
  lines.push(`${INDENT}${BEGIN}`);
  lines.push(
    `${INDENT}<!-- Portfolio project slot pool. Eight dormant freejoint capsules parked`,
  );
  lines.push(
    `${INDENT}     well below the floor. ProjectSystem claims a slot on demand, teleports`,
  );
  lines.push(
    `${INDENT}     it into the scene, and attaches a procedural Three.js mesh group on`,
  );
  lines.push(
    `${INDENT}     top. Empty slots stay parked at z=-60 so they never render or collide`,
  );
  lines.push(`${INDENT}     visibly with anything. -->`);
  for (let i = 0; i < SLOT_COUNT; i++) lines.push(slotLine(i));
  lines.push(`${INDENT}${END}`);
  const block = lines.join(eol);

  // Walk back from beginIdx to strip any indent on the marker's own line.
  const beginLineStart = xml.lastIndexOf("\n", beginIdx - 1) + 1;
  const head = xml.slice(0, beginLineStart);

  // Walk forward from endIdx past the closing tag and the rest of that line.
  const endLineEnd = xml.indexOf("\n", endIdx);
  const tail = endLineEnd === -1 ? "" : xml.slice(endLineEnd);

  const next = head + block + tail;

  if (next === xml) {
    process.stdout.write("regen-slots: no change\n");
    return;
  }

  writeFileSync(XML_PATH, next, "utf8");
  process.stdout.write(`regen-slots: wrote ${SLOT_COUNT} slots\n`);
}

main();
