// scripts/regen-slots.mjs
//
// Regenerates the <!-- SLOT_BLOCK_BEGIN --> / <!-- SLOT_BLOCK_END --> region
// of assets/scenes/humanoid.xml. Emits exactly SLOT_COUNT = 8 slots.
// Idempotent — running twice produces byte-identical output.
//
// The per-slot z offset uses integer values for even i and half-step decimals
// for odd i ("-60", "-60.5", "-61", "-61.5", …) to match the current hand-
// written block byte-for-byte. The initial run against the pre-marker XML
// must produce no diff.
//
// See docs/superpowers/specs/2026-04-24-project-sprite-workflow-design.md §4.5.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const XML_PATH = resolve(__dirname, "..", "assets", "scenes", "humanoid.xml");

const SLOT_COUNT = 8;
const BEGIN = "<!-- SLOT_BLOCK_BEGIN — regenerated by scripts/regen-slots.mjs, do not edit by hand -->";
const END = "<!-- SLOT_BLOCK_END -->";
const INDENT = "    ";

function slotZ(i) {
  // i=0 → "-60", i=1 → "-60.5", i=2 → "-61", i=3 → "-61.5", …
  return i % 2 === 0 ? String(-60 - i * 0.5) : (-60 - i * 0.5).toFixed(1);
}

function slotLine(i) {
  // contype=2 conaffinity=1 is the physics-agent's static collision filter
  // (commit 010a20b on mujoco-portfolio). Pairwise rule: (a.contype &
  // b.conaff) | (b.contype & a.conaff). Slot-slot = 0, slot-floor = 1,
  // slot-humanoid = 1. Parked slots never inter-penetrate but live slots
  // still collide with floor and ragdoll. NO runtime toggle needed —
  // DO NOT CHANGE these attributes.
  return (
    `${INDENT}<body name="project_slot_${i}" pos="0 0 ${slotZ(i)}">` +
    `<freejoint/>` +
    `<geom type="capsule" fromto="0 0 -0.22 0 0 0.22" size="0.26" ` +
    `rgba="0.85 0.18 0.20 1" mass="2.5" friction="1.0 0.05 0.002" ` +
    `contype="2" conaffinity="1"/>` +
    `</body>`
  );
}

function main() {
  const xml = readFileSync(XML_PATH, "utf8");

  // Preserve the file's line-ending convention so git doesn't report a
  // whitespace diff just from rewriting. Detect CRLF vs LF from the first
  // line break.
  const eol = xml.includes("\r\n") ? "\r\n" : "\n";

  const beginIdx = xml.indexOf(BEGIN);
  const endIdx = xml.indexOf(END);
  if (beginIdx === -1 || endIdx === -1) {
    console.error(
      "regen-slots: SLOT_BLOCK markers not found in assets/scenes/humanoid.xml",
    );
    process.exit(1);
  }
  if (endIdx < beginIdx) {
    console.error("regen-slots: SLOT_BLOCK_END appears before SLOT_BLOCK_BEGIN");
    process.exit(1);
  }

  // Rebuild the block, indented with 4 spaces, each line joined by the file's
  // native EOL. The marker comments themselves sit on their own lines at the
  // same indent level as the bodies.
  const lines = [];
  lines.push(`${INDENT}${BEGIN}`);
  lines.push(`${INDENT}<!-- Portfolio project slot pool. Eight dormant freejoint capsules parked`);
  lines.push(`${INDENT}     well below the floor. Collision mask trick: slot geoms have`);
  lines.push(`${INDENT}     contype=2 conaffinity=1. Floor + humanoid default to contype=1`);
  lines.push(`${INDENT}     conaffinity=1. Pairwise collision requires (a.contype & b.conaff)`);
  lines.push(`${INDENT}     OR (b.contype & a.conaff):`);
  lines.push(`${INDENT}       slot-floor : (2 & 1) | (1 & 1) = 0 | 1 = 1 → collide ✓`);
  lines.push(`${INDENT}       slot-slot  : (2 & 1) | (2 & 1) = 0 | 0 = 0 → no collide ✓`);
  lines.push(`${INDENT}       slot-torso : (2 & 1) | (1 & 1) = 0 | 1 = 1 → collide ✓`);
  lines.push(`${INDENT}     So parked slots can stack on the same axis without generating`);
  lines.push(`${INDENT}     dozens of inter-penetrating contacts (which otherwise explodes the`);
  lines.push(`${INDENT}     sim to NaN on frame 1 and the humanoid launches), but spawned`);
  lines.push(`${INDENT}     projects still land on the floor and interact with the ragdoll.`);
  lines.push(`${INDENT}     NO runtime toggle needed — the mask is correct for both states.`);
  lines.push(`${INDENT}     **DO NOT CHANGE contype/conaffinity ON THESE GEOMS.** -->`);
  for (let i = 0; i < SLOT_COUNT; i++) lines.push(slotLine(i));
  lines.push(`${INDENT}${END}`);
  const block = lines.join(eol);

  // Walk back from beginIdx to strip any indent on the marker's own line.
  const beginLineStart = xml.lastIndexOf("\n", beginIdx - 1) + 1;
  const head = xml.slice(0, beginLineStart);

  // Walk forward from endIdx past the closing tag and the rest of that line.
  const endLineEnd = xml.indexOf("\n", endIdx);
  const tail = endLineEnd === -1 ? "" : xml.slice(endLineEnd);

  const next = head + block + tail;

  if (next === xml) {
    process.stdout.write("regen-slots: no change\n");
    return;
  }

  writeFileSync(XML_PATH, next, "utf8");
  process.stdout.write(`regen-slots: wrote ${SLOT_COUNT} slots\n`);
}

main();
